version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  default: none
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Examine Go source code and report suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes stylecheck + gosimple in v2)
    - unused        # Check for unused code

    # Code quality
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues

    # Complexity
    - gocyclo       # Computes cyclomatic complexity
    - gocognit      # Computes cognitive complexity

    # Security
    - gosec         # Inspects source code for security problems

    # Performance
    - prealloc      # Finds slice declarations that could potentially be preallocated

    # Style
    - whitespace    # Detection of leading and trailing whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.DB).Close

    govet:
      enable-all: true
      disable:
        - shadow        # Reports variables that shadow other variables
        - fieldalignment # Too noisy for structs

    gocyclo:
      min-complexity: 10

    gocognit:
      min-complexity: 10

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - hugeParam

    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: unexported-return
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: superfluous-else
        - name: unreachable-code

    gosec:
      excludes:
        - G404 # Use of weak random number generator - acceptable for non-crypto use
      config:
        global:
          audit: true

    staticcheck:
      checks:
        - all
        - '-ST1003'  # Should not use underscores in Go names (allow for test names)

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec
          - gocritic
          - funlen
          - gocognit

      # Exclude E2E test files from certain checks
      - path: e2e_.*_test\.go
        linters:
          - gocyclo
          - gocognit
          - funlen
          - gocritic

      # Allow underscores in test names
      - path: _test\.go
        text: "should not use underscores"

      # Exclude known issues in generated code
      - path: .*_generated\.go
        linters:
          - all

formatters:
  enable:
    - gofmt         # Standard Go formatter
    - goimports     # Organizes imports

  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
  sort-order:
    - linter
    - severity
    - file
